In [2]:
import pandas as pd
import numpy as np

data = {
    'name': ['Amit', 'Priya', 'Amit', 'Ravi', 'Sneha', None, 'Ravi'],
    'age': [25, 30, 25, np.nan, 28, 35, 40],
    'city': ['Hyderabad', 'Pune', 'Hyderabad', 'Delhi', None, 'Mumbai', 'Delhi'],
    'salary': [45000, 60000, 45000, 55000, 50000, 70000, 55000]
    
}
df = pd.DataFrame(data)
df

    name   age       city  salary
0   Amit  25.0  Hyderabad   45000
1  Priya  30.0       Pune   60000
2   Amit  25.0  Hyderabad   45000
3   Ravi   NaN      Delhi   55000
4  Sneha  28.0        NaN   50000
5    NaN  35.0     Mumbai   70000
6   Ravi  40.0      Delhi   55000

In [3]:
df.isna().sum()

name      1
age       1
city      1
salary    0
dtype: int64

In [4]:

df['age'] = df['age'].fillna(0)
df['name'] = df['name'].fillna('Unknown')
df['city'] = df['city'].fillna('Unknown')
df

      name   age       city  salary
0     Amit  25.0  Hyderabad   45000
1    Priya  30.0       Pune   60000
2     Amit  25.0  Hyderabad   45000
3     Ravi   0.0      Delhi   55000
4    Sneha  28.0    Unknown   50000
5  Unknown  35.0     Mumbai   70000
6     Ravi  40.0      Delhi   55000

In [6]:
df.duplicated().sum()

np.int64(1)

In [7]:

df = df.drop_duplicates()
df

      name   age       city  salary
0     Amit  25.0  Hyderabad   45000
1    Priya  30.0       Pune   60000
3     Ravi   0.0      Delhi   55000
4    Sneha  28.0    Unknown   50000
5  Unknown  35.0     Mumbai   70000
6     Ravi  40.0      Delhi   55000

In [8]:
# %%
df.groupby('city').size()

city
Delhi        2
Hyderabad    1
Mumbai       1
Pune         1
Unknown      1
dtype: int64

In [9]:
# %%
df.groupby('city')['salary'].sum()

city
Delhi        110000
Hyderabad     45000
Mumbai        70000
Pune          60000
Unknown       50000
Name: salary, dtype: int64

In [10]:
# %%
df.groupby('city')['salary'].max()

city
Delhi        55000
Hyderabad    45000
Mumbai       70000
Pune         60000
Unknown      50000
Name: salary, dtype: int64

In [11]:
df.sort_values('salary')

      name   age       city  salary
0     Amit  25.0  Hyderabad   45000
4    Sneha  28.0    Unknown   50000
3     Ravi   0.0      Delhi   55000
6     Ravi  40.0      Delhi   55000
1    Priya  30.0       Pune   60000
5  Unknown  35.0     Mumbai   70000

In [13]:
df.sort_values('salary' ,ascending=False)

      name   age       city  salary
5  Unknown  35.0     Mumbai   70000
1    Priya  30.0       Pune   60000
6     Ravi  40.0      Delhi   55000
3     Ravi   0.0      Delhi   55000
4    Sneha  28.0    Unknown   50000
0     Amit  25.0  Hyderabad   45000

In [16]:
df.sort_values(['city' ,'salary'],ascending =[True , False])

      name   age       city  salary
3     Ravi   0.0      Delhi   55000
6     Ravi  40.0      Delhi   55000
0     Amit  25.0  Hyderabad   45000
5  Unknown  35.0     Mumbai   70000
1    Priya  30.0       Pune   60000
4    Sneha  28.0    Unknown   50000